[package]
name = "containerd-shim-spin-v2"
version = "0.13.1"
authors = ["SpinKube Engineering Team"]
edition = "2021"
repository = 'https://github.com/spinkube/containerd-shim-spin'
license = "Apache-2.0"
homepage = 'https://github.com/spinkube/containerd-shim-spin'
description = """
Containerd shim for running Spin workloads.
"""

[dependencies]
containerd-shim-wasm = "0.5.0"
containerd-shim = "0.7.1"
log = "0.4"
spin-app = { git = "https://github.com/calebschoepp/spin", rev = "f1ffcd9cf705729ae16c60fbcb76399bdcefe3c7" }
spin-core = { git = "https://github.com/calebschoepp/spin", rev = "f1ffcd9cf705729ae16c60fbcb76399bdcefe3c7" }
spin-componentize = { git = "https://github.com/fermyon/spin-componentize", rev = "191789170abde10cd55590466c0660dd6c7d472a" }
# Enable loading components precompiled by the shim
spin-trigger = { git = "https://github.com/calebschoepp/spin", rev = "f1ffcd9cf705729ae16c60fbcb76399bdcefe3c7", features = ["unsafe-aot-compilation"] }
spin-trigger-http = { git = "https://github.com/calebschoepp/spin", rev = "f1ffcd9cf705729ae16c60fbcb76399bdcefe3c7" }
spin-trigger-redis = { git = "https://github.com/calebschoepp/spin", rev = "f1ffcd9cf705729ae16c60fbcb76399bdcefe3c7" }
trigger-sqs = { git = "https://github.com/kate-goldenring/spin-trigger-sqs", rev = "f4369627fbfb9a517ff8d60276f5271af72b31f4", default-features = false}
spin-manifest = { git = "https://github.com/calebschoepp/spin", rev = "f1ffcd9cf705729ae16c60fbcb76399bdcefe3c7" }
spin-loader = { git = "https://github.com/calebschoepp/spin", rev = "f1ffcd9cf705729ae16c60fbcb76399bdcefe3c7" }
spin-oci = { git = "https://github.com/calebschoepp/spin", rev = "f1ffcd9cf705729ae16c60fbcb76399bdcefe3c7" }
spin-common = { git = "https://github.com/calebschoepp/spin", rev = "f1ffcd9cf705729ae16c60fbcb76399bdcefe3c7" }
spin-telemetry = { git = "https://github.com/calebschoepp/spin", rev = "f1ffcd9cf705729ae16c60fbcb76399bdcefe3c7" }
spin-expressions = { git = "https://github.com/calebschoepp/spin", rev = "f1ffcd9cf705729ae16c60fbcb76399bdcefe3c7" }
wasmtime = "18.0.1"
tokio = { version = "1", features = ["rt"] }
openssl = { version = "*", features = ["vendored"] }
serde = "1.0"
serde_json = "1.0"
url = "2.3"
anyhow = "1.0"
oci-spec = { version = "0.6.3" }
futures = "0.3"
ctrlc = { version = "3.2", features = ["termination"] }


[dev-dependencies]
wat = "1"
